/// <reference path="../.astro/types.d.ts" />
/// <reference types="astro/client" />

// Env bindings — auto-generated by `wrangler types` (DO NOT hand-edit)
// Run: npm run types

interface Env {
  // D1
  DB: D1Database;

  // KV (for event dedup)
  DEDUP: KVNamespace;

  // R2 / Assets
  ASSETS: Fetcher;

  // Vars
  SITE_URL: string;
  META_PIXEL_ID: string;
  META_API_VERSION: string;
  ALLOWED_ORIGIN: string;
  ENVIRONMENT: string;

  // Secrets (set via `wrangler secret put`)
  META_ACCESS_TOKEN: string;
  SHEETS_WEBHOOK_URL?: string;
  ADMIN_API_KEY: string;
}
